version: '3.8'
networks:
  gorillanet:

services:
  nginx:
    image: nginx:stable-alpine
    depends_on:
      - npm
    networks:
      - gorillanet
    container_name: nginx_gorillanet
    restart: unless-stopped
    ports:
      - "3000:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  npm:
    image: node:current-alpine
    container_name: npm_gorillanet
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    entrypoint: [ 'npm' ]
