version: '3.9'
networks:
  gorillanet:

services:
  nginx:
    profiles: ["prod"]
    image: nginx:stable-alpine
    depends_on:
      - npm
    networks:
      - gorillanet
    container_name: nginx_gorillanet
    restart: unless-stopped
    ports:
      - "3000:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  npm:
    profiles: [ "prod" ]
    image: node:current-alpine
    container_name: npm_gorillanet
    networks:
      - gorillanet
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    entrypoint: [ 'npm','run','build' ]
  npmdev:
    profiles: [ "dev" ]
    image: node:current-alpine
    container_name: npmdev_gorillanet
    networks:
      - gorillanet
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    ports:
      - "3000:3000"
      - "24678:24678"
    entrypoint: [ 'npm','run','dev','--','--host' ]
